export type SiteConfig = typeof siteConfig;

export const siteConfig = {
  name: "ExcelFormulaGPT",
  url: "excelformulagpt.com",
  title: "Excel Formula GPT - AI Excel Formula Generator",
  description:
    "Free AI-powered Excel formula generator that converts your natural language descriptions into accurate Excel formulas instantly.",
  keywords: [
    "Excel formula generator",
    "Free Excel formula generator",
    "excel formula for multiplication",
    "excel formula to count days from date to today automatically",
    "excel formula not calculating",
    "Excel formula AI",
    "Excel formula helper",
    "Excel formula converter",
    "Excel formula assistant",
    "Excel function generator",
    "Excel formula translator",
    "AI Excel helper",
    "Excel formula builder",
    "Excel formula creator",
    "Excel formula examples",
    "Excel formula guide",
    "Excel formula solutions",
    "Excel formula automation",
    "Excel formula tool",
    "Excel formula converter online",
    "Excel formula generator free",
    "Excel formula writing tool",
    "Excel formula maker",
    "Excel formula AI assistant",
  ],
  twitter: "https://twitter.com/chaoying972",
  domain: "www.excelformulagpt.com",
};
